##--------------------------------------------------------------------------------
## SSH public key authentication.
##--------------------------------------------------------------------------------
#- name: Set authorized_keys for {{ PKG_USER }}...
#  authorized_key:
#    user: "{{ PKG_USER }}"
#    key: "{{ item }}"
#  with_items:
#     - "{{ pkg_user_authorized_keys }}"
#
#- name: Copy private key for {{ PKG_USER }}...
#  copy:
#    content: "{{ pkg_user_id_rsa }}"
#    dest:    "/home/{{ PKG_USER }}/.ssh/id_rsa"
#    owner:   "{{ PKG_USER }}"
#    mode:    "0600"
#
#- name: Set authorized_keys for {{ SYS_USER }}...
#  authorized_key:
#    user: "{{ SYS_USER }}"
#    key: "{{ item }}"
#  with_items:
#     - "{{ sys_user_authorized_keys }}"
#
## Copy private key after authorized_keys so that .ssh directory is created before.
#- name: Copy private key for {{ SYS_USER }}...
#  copy:
#    content: "{{ sys_user_id_rsa }}"
#    dest:    "/home/{{ SYS_USER }}/.ssh/id_rsa"
#    owner:   "{{ SYS_USER }}"
#    mode:    "0600"
#
#- name: Copy DECRYPT_KEY_FILE to {{ SYS_USER }}...
#  copy:
#    content: "{{ decrypt_key }}"
#    dest:    "{{ DECRYPT_KEY_FILE }}"
#    owner:   "{{ SYS_USER }}"
#    mode:    "0640"
#
##- name: Set authorized_keys for users...
##  authorized_key:
##    user: "{{ item.0.name }}"
##    key:  "{{ lookup('file', item.1) }}"
##  with_subelements:
##     - "{{ users }}"
##     - authorized
##
##- name: Copy private keys...
##  copy:
##    src:   "{{ item.1 }}"
##    dest:  "/home/{{ item.0.name }}/.ssh/private.pem"
##    owner: "{{ item.0.name }}"
##    group: "{{ K8S_GROUP }}"
##    mode:  "0600"
##  with_subelements:
##    - "{{ users }}"
##    - private_key
##    - flags:
##      skip_missing: true
##  when: true
#
##--------------------------------------------------------------------------------
## Sudo setup for the user not to be asked for password.
##--------------------------------------------------------------------------------
#- name: Create entries under /etc/suders.d for users for no password sudo.
#  shell: "echo '{{ item.name }} ALL=(ALL:ALL) NOPASSWD:ALL' > {{ item.name }}"
#  args:
#    chdir:   /etc/sudoers.d/
#    creates: "{{ item.name }}"
#  with_items:
#    - "{{ users }}"
#
#- name: Verify if files are created.
#  shell: "grep {{ item.name }} {{ item.name }}"
#  args:
#    chdir: /etc/sudoers.d/
#  with_items:
#    - "{{ users }}"
#  ignore_errors: no
