#--------------------------------------------------------------------------------
# kube-proxy utilizes iptables to control the pod network traffic.
# - kubernetes.io/docs/concepts/cluster-administration/network-plugins/
# - https://wiki.libvirt.org/page/Net.bridge.bridge-nf-call_and_sysctl.conf
#--------------------------------------------------------------------------------
- name: "Enable pod network traffic procssing in iptables."
  shell:
    cmd: |
      sudo tee /etc/sysctl.d/k8s.conf <<EOF
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      EOF

- name: Reload sysctl
  shell: |
    sysctl --system
    sudo sysctl -a
