#--------------------------------------------------------------------------------
# Remove swap from fstab
# Make sure to reboot! Hence run this as the last step of OS module.
#--------------------------------------------------------------------------------
- name: swap - remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap '
    state: absent

- name: Restart server
  command: /sbin/shutdown -r 1
  async: 0
  poll: 0
  ignore_errors: true

- pause:
    prompt: "The system has restarted to complete disabling swap (otherwise error with kubeadm)..."
    minutes: 1

