- name: NGINX site provisioning.
  include_role:
    name: williamyeh.nginx
  vars:
    #nginx_version: 1.8.1
    # TO BE
    nginx_conf_main: "templates/nginx.conf.j2"
    #nginx_conf_main: "templates/nginx.conf"
    nginx_conf_others:
      conf_template_for_app_1:
        src: "templates/site.conf.j2"
        dest: site.conf

- name: Assure nginx ssl directory.
  file:
    path: "{{ nginx_conf_dir }}/ssl"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy SSL certificates to /etc/nginx/ssl directory.
  copy:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
   - { src: 'ssl.key', dest: '{{ nginx_conf_dir}}/ssl' }
   - { src: 'ssl.crt', dest: '{{ nginx_conf_dir}}/ssl' }

