#--------------------------------------------------------------------------------
# AWS CLI installation (global site-package)
# https://pypi.org/project/awscli/
# https://docs.aws.amazon.com/cli/latest/userguide/installing.html
#--------------------------------------------------------------------------------
- name: AWS CLI install
  pip:
    name: "awscli"
    state: present
    # https://unix.stackexchange.com/questions/429717
    extra_args: "--upgrade --force-reinstall"

- name: AWS CLI validation
  command: "aws --version"
  register: awscli_version

- fail:
    msg: "AWS CLI installation failed"
  when: awscli_version.rc != 0

- debug:
    msg: "{{ awscli_version.stdout }}"