drawio_package_name: "draw.io"
drawio_package_format: "deb"
drawio_version: "12.6.5"
drawio_arch: "amd64"
drawio_package_url: "https://github.com/jgraph/drawio-desktop/releases/download/v{{ drawio_version }}/{{ drawio_package_name }}-{{ drawio_arch }}-{{drawio_version}}.{{ drawio_package_format }}"
