#--------------------------------------------------------------------------------
# Docker group and its users to avoid using root/sudo for the users.
# Beware of the risk of users being able to access the docker socket.
# https://www.projectatomic.io/blog/2015/08/
# why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/
#--------------------------------------------------------------------------------
- name: "Create group docker..."
  group:
    name: "{{ DOCKER_GROUP }}"
    state: present

- include_vars:  "{{ ansible_distribution }}.yml"
- include_tasks: "{{ ansible_distribution }}.yml"

